config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-linen-cockroach.sh
        container: qc.acc_cranky-azure-balinese
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-linen-angora.sh
        container: qc.doc_hilly-gold-centipede
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-tomato-newt.sh
        container: qc.doc_ready-corn-squirt
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-amber-hummingbird.sh
        container: qc.doc_grumpy-thistle-newfoundland
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-chartreuse-dingo.sh
        container: qc.lic_sloppy-peach-malamute
  QC.Sec:
    repos:
      github.com/darce-i3m/sqaaas-web gosec:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-viridian-bracke.sh
        container: qc.sec_surly-wheat-mastiff
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-ochre-vulture.sh
        container: qc.sty_thirsty-heliotrope-quokka
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-tomato-toad.sh
        container: qc.ver_tacky-olive-tarantula
timeout: 1800
