config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-firebrick-kiwi.sh
        container: qc.acc_squeaky-ochre-whippet
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-periwinkle-whale.sh
        container: qc.doc_scummy-khaki-cow
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-maroon-sheep.sh
        container: qc.doc_smelly-red-paradise
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-magenta-neanderthal.sh
        container: qc.doc_lanky-zucchini-woodlouse
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/sqaaas-web F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-malachite-butterfly.sh
        container: qc.fair_surly-myrtle-buzzard
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-yellow-indri.sh
        container: qc.lic_flimsy-ecru-saola
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-mauve-abyssinian.sh
        container: qc.ver_ugly-indigo-chihuahua
timeout: 1800
