config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-saffron-clam.sh
        container: qc.acc_gamy-myrtle-hyena
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-ivory-mongoose.sh
        container: qc.doc_droopy-violet-indri
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-indigo-bordeaux.sh
        container: qc.doc_chummy-ecru-dachsbracke
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chartreuse-raccoon.sh
        container: qc.doc_skinny-zucchini-skunk
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-thistle-badger.sh
        container: qc.lic_cloudy-russet-tang
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-bistre-hedgehog.sh
        container: qc.sty_hilly-orange-otter
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-maroon-buzzard.sh
        container: qc.sty_wheezy-yellow-wolfhound
      github.com/EOSC-synergy/sqaaas-web stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-rose-quokka.sh
        container: qc.sty_seedy-black-catfish
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-amaranth-gopher.sh
        container: qc.ver_lanky-wheat-cattle
timeout: 5400
