config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-taupe-mule.sh
        container: qc.acc_shaky-plum-hummingbird
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-violet-coati.sh
        container: qc.doc_sleazy-rose-devil
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-yellow-quoll.sh
        container: qc.doc_wheezy-mauve-chinook
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-rose-wolf.sh
        container: qc.doc_chewy-pink-gar
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-web F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-beige-hyena.sh
        container: qc.fair_stinky-firebrick-angelfish
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-firebrick-hornet.sh
        container: qc.lic_randy-white-octopus
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-carmine-budgerigar.sh
        container: qc.ver_sloppy-mustard-mau
timeout: 1800
