config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-mustard-terrier.sh
        container: qc.acc_flabby-emerald-bloodhound
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-grey-fly.sh
        container: qc.doc_homely-cornflower-flamingo
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-periwinkle-setter.sh
        container: qc.doc_skimpy-chestnut-ray
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-heliotrope-molly.sh
        container: qc.doc_squirrely-harlequin-barb
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/sqaaas-web F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cobalt-numbat.sh
        container: qc.fair_homey-chestnut-bee
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-scarlet-sheep.sh
        container: qc.lic_slimy-ruby-newfoundland
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-orange-javanese.sh
        container: qc.ver_snoopy-black-rhinoceros
timeout: 1800
