config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-black-bee.sh
        container: qc.acc_zippy-magenta-emu
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-rose-uakari.sh
        container: qc.doc_snoopy-black-barb
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-silver-iguana.sh
        container: qc.doc_nippy-purple-slug
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-saffron-cuttlefish.sh
        container: qc.doc_ready-heliotrope-cheetah
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-web F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-charcoal-millipede.sh
        container: qc.fair_lumpy-pink-armadillo
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-persimmon-bobcat.sh
        container: qc.lic_queasy-persimmon-caiman
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-copper-tetra.sh
        container: qc.ver_crabby-plum-bee
timeout: 1800
