config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-brass-angora.sh
        container: qc.acc_leaky-rose-eagle
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-denim-camel.sh
        container: qc.doc_silly-turquoise-tuatara
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-chocolate-sponge.sh
        container: qc.doc_slimy-goldenrod-hummingbird
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-harlequin-baboon.sh
        container: qc.doc_stinky-fuchsia-chinchilla
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-web F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-ivory-barnacle.sh
        container: qc.fair_pokey-olivine-jackal
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-pumpkin-rottweiler.sh
        container: qc.lic_seedy-celadon-gorilla
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-gamboge-spaniel.sh
        container: qc.ver_lanky-crimson-indri
timeout: 1800
