config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-teal-axolotl.sh
        container: qc.acc_messy-viridian-shark
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-aquamarine-heron.sh
        container: qc.doc_scanty-turquoise-numbat
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-scarlet-monkey.sh
        container: qc.doc_sleazy-wheat-ibis
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-grey-woodpecker.sh
        container: qc.doc_cheeky-orange-frog
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/sqaaas-web F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-red-kiwi.sh
        container: qc.fair_sunny-persimmon-tetra
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-eggplant-beagle.sh
        container: qc.lic_scanty-lilac-rabbit
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-khaki-bat.sh
        container: qc.ver_hasty-aqua-mayfly
timeout: 1800
