config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-gold-serval.sh
        container: qc.acc_gummy-celadon-spoonbill
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-lemon-scorpion.sh
        container: qc.doc_messy-gold-discus
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-russet-lion.sh
        container: qc.doc_chewy-charcoal-dane
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-rust-dormouse.sh
        container: qc.doc_woozy-pear-beetle
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-vermilion-capybara.sh
        container: qc.lic_frumpy-carmine-bee
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-xanthic-budgerigar.sh
        container: qc.sty_stuffy-plum-leopard
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-tangerine-audemer.sh
        container: qc.sty_silly-periwinkle-hornet
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-lemon-tarsier.sh
        container: qc.ver_pasty-gold-koala
timeout: 1800
