config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-seashell-hippopotamus.sh
        container: qc.acc_droopy-orange-jellyfish
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lilac-beetle.sh
        container: qc.doc_wimpy-lime-mole
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-peach-hare.sh
        container: qc.doc_cranky-crimson-heron
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-lilac-indri.sh
        container: qc.doc_muggy-denim-dhole
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-web F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-chocolate-audemer.sh
        container: qc.fair_beady-corn-caterpillar
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-harlequin-turkey.sh
        container: qc.lic_sickly-plum-dog
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-maroon-frigatebird.sh
        container: qc.ver_muggy-celadon-boar
timeout: 1800
