config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-persimmon-bandicoot.sh
        container: qc.acc_flaky-tan-crane
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-turquoise-rhinoceros.sh
        container: qc.doc_wimpy-smalt-dhole
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-vermilion-saola.sh
        container: qc.doc_seedy-razzmatazz-nightingale
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-sepia-oyster.sh
        container: qc.doc_woozy-harlequin-elephant
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-chartreuse-angora.sh
        container: qc.lic_leaky-harlequin-budgerigar
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-salmon-cattle.sh
        container: qc.met_foggy-platinum-toucan
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cinnabar-ostrich.sh
        container: qc.sty_stealthy-cinnamon-zebra
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-ochre-horse.sh
        container: qc.sty_wheezy-jade-barb
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-magenta-cheetah.sh
        container: qc.ver_snazzy-zucchini-ragdoll
timeout: 5400
