config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-xanthic-tetra.sh
        container: qc.acc_shabby-wheat-beagle
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-silver-lizard.sh
        container: qc.doc_messy-xanthic-hedgehog
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-salmon-mammoth.sh
        container: qc.doc_frumpy-cyan-ibis
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-denim-llama.sh
        container: qc.doc_scummy-ecru-corgi
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-celadon-dalmatian.sh
        container: qc.lic_gummy-zucchini-gar
  QC.Sec:
    repos:
      github.com/darce-i3m/sqaaas-web gosec:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-amethyst-tapir.sh
        container: qc.sec_lumpy-tan-starfish
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-vermilion-affenpinscher.sh
        container: qc.sty_frumpy-heliotrope-wallaby
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-peach-mist.sh
        container: qc.ver_pokey-goldenrod-dunker
timeout: 1800
