config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-russet-kiwi.sh
        container: qc.acc_surly-teal-toad
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-aqua-zorse.sh
        container: qc.doc_slaphappy-orange-newfoundland
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-orchid-malamute.sh
        container: qc.doc_bluesy-mauve-weasel
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-saffron-flounder.sh
        container: qc.doc_breezy-grey-echidna
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-charcoal-tzu.sh
        container: qc.lic_foggy-ochre-bombay
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-alizarin-panda.sh
        container: qc.met_goopy-yellow-ragdoll
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-jade-quoll.sh
        container: qc.sty_cranky-sapphire-affenpinscher
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-taupe-wildebeest.sh
        container: qc.sty_nerdy-scarlet-toucan
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-rust-ostrich.sh
        container: qc.ver_cloudy-maroon-uguisu
timeout: 5400
