config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-wisteria-sponge.sh
        container: qc.acc_slimy-violet-hound
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-mustard-bandicoot.sh
        container: qc.doc_foggy-viridian-bonobo
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-flax-capuchin.sh
        container: qc.doc_woolly-carmine-shrew
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-carmine-giraffe.sh
        container: qc.doc_surly-cerise-albatross
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-firebrick-hedgehog.sh
        container: qc.lic_scanty-cyan-quoll
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-salmon-baboon.sh
        container: qc.sty_shaky-ivory-russel
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-maroon-cuscus.sh
        container: qc.sty_flimsy-vermilion-crocodile
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-pink-toad.sh
        container: qc.ver_gummy-magnolia-rabbit
timeout: 5400
