config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-zucchini-robin.sh
        container: qc.acc_chewy-green-starfish
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-chocolate-ferret.sh
        container: qc.doc_skanky-dandelion-bonobo
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-celadon-dogfish.sh
        container: qc.doc_droopy-aqua-dolphin
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-maroon-seal.sh
        container: qc.doc_seedy-charcoal-chameleon
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-indigo-iguana.sh
        container: qc.lic_boozy-lemon-sloth
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-buff-meerkat.sh
        container: qc.sty_ready-seashell-dragonfly
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-mustard-penguin.sh
        container: qc.sty_trippy-black-whale
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-lime-chameleon.sh
        container: qc.ver_slimy-celadon-caterpillar
timeout: 1800
