config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-teal-sparrow.sh
        container: qc.acc_fuzzy-cinnabar-collie
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-teal-zebra.sh
        container: qc.doc_sleepy-azure-cheetah
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-chocolate-wolfhound.sh
        container: qc.doc_boozy-silver-harrier
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-chartreuse-hyrax.sh
        container: qc.doc_grumpy-purple-tarantula
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-zucchini-dingo.sh
        container: qc.lic_wheezy-carmine-seal
  QC.Sec:
    repos:
      github.com/darce-i3m/sqaaas-web gosec:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-turquoise-monster.sh
        container: qc.sec_pokey-cinnamon-hound
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.homely-alizarin-squirrel.sh
        container: qc.sty_cozy-peach-coati
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-tomato-cichlid.sh
        container: qc.ver_boozy-magenta-burmese
timeout: 1800
