config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-pear-terrier.sh
        container: qc.acc_seedy-sepia-tzu
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-alizarin-jackal.sh
        container: qc.doc_crabby-vermilion-javanese
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ultramarine-okapi.sh
        container: qc.doc_snazzy-white-cat
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-sepia-termite.sh
        container: qc.doc_snoopy-red-mandrill
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-corn-gharial.sh
        container: qc.lic_wiggy-ochre-tapir
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-brass-affenpinscher.sh
        container: qc.sty_gloppy-chestnut-corgi
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-ultramarine-emu.sh
        container: qc.sty_scaly-charcoal-coati
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-indigo-ibis.sh
        container: qc.ver_boozy-azure-skunk
timeout: 5400
