config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sepia-kingfisher.sh
        container: qc.acc_tacky-indigo-sloth
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-champagne-binturong.sh
        container: qc.doc_scummy-myrtle-wolf
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-saffron-butterfly.sh
        container: qc.doc_boozy-maroon-baboon
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cerise-moth.sh
        container: qc.doc_lovely-buff-mau
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-lavender-shark.sh
        container: qc.lic_slimy-teal-crane
  QC.Sec:
    repos:
      github.com/darce-i3m/sqaaas-web gosec:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-harlequin-paradise.sh
        container: qc.sec_skanky-goldenrod-quail
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-crimson-angora.sh
        container: qc.sty_leaky-taupe-rhinoceros
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-asparagus-ostrich.sh
        container: qc.ver_shabby-aquamarine-terrier
timeout: 1800
