config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-turquoise-ostrich.sh
        container: qc.acc_surly-charcoal-squirrel
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-red-stingray.sh
        container: qc.doc_frumpy-puce-bird
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cinnamon-dog.sh
        container: qc.doc_jumpy-mauve-leopard
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-sepia-seahorse.sh
        container: qc.doc_craggy-violet-affenpinscher
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-ivory-wolverine.sh
        container: qc.lic_queasy-persimmon-binturong
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-olivine-crab.sh
        container: qc.sty_wimpy-gold-olm
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-heliotrope-kingfisher.sh
        container: qc.sty_snazzy-razzmatazz-llama
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-olive-moose.sh
        container: qc.ver_bumpy-tangerine-foxhound
timeout: 5400
